print("Hi! Let's play Mad Libs. Give me a color:")
color = input("> ")
print("\nNice! Next, a plural noun:")
noun = input("> ")
print("\nAlright. Finally, a celebrity:")
celebrity = input("> ")

print("\nRoses are " + color)
print(noun + " are blue")
print("I love " + celebrity)
